### ISSUE TITLE
Version 0.2.2 Run "reset now" Lost coin

### ISSUE THREAD

**Issue by lqy169** [leviarcoin/leviarcoin-gui-wallet#1]
After updating to version 0.2.2, I ran "reset now" and all received coins before the 337000 block were not added to the balance. Only the coins received after 337,000 blocks appear in the balance. why?

**Comment by marki555** [comment]
I have similar issue both with GUI wallet and simplewallet. After "reset" I see only last few transactions on my balance. Is there any fix for this?

**Comment by BKdilse** [comment]
Did you guys find a fix for this?

Lack of support is a concern here.

**Comment by markmatroska** [comment]
We released a new version 0.3.0 to fix the issues. Now you can find a newer version (18.06 sources). Binaries will be released in the next days. I close this.
