### ISSUE TITLE
Issue while building Leviar GUI 18.06 on Windows

### ISSUE THREAD

**Issue by Firefds** [leviarcoin/leviarcoin-gui-wallet#3]
I Followed the readme step by step for building under windows.
When I perform this step:
`./build.sh`

I get the following errors:

```
$ ./build.sh
Building release
~/leviarcoin-gui-wallet ~/leviarcoin-gui-wallet
~/leviarcoin-gui-wallet ~/leviarcoin-gui-wallet
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
You are currently on commit 6a15368
Cannot determine most recent tag. Make sure that you are building either from a Git working tree or from a source archive.
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
libwallet_merged.a not found - Building libwallet
./get_libwallet_api.sh: line 82: /home/Shauli/leviarcoin-gui-wallet/monero/version.sh: Not a directory
Building libwallet release
cleaning up existing monero build dir, libs and includes
mkdir: cannot create directory ‘/home/Shauli/leviarcoin-gui-wallet/monero’: Not a directory
./get_libwallet_api.sh: line 129: pushd: /home/Shauli/leviarcoin-gui-wallet/monero/build/release: Not a directory
Unknown platform, configuring general build
./get_libwallet_api.sh: line 204: cmake: command not found
./get_libwallet_api.sh: line 215: pushd: /home/Shauli/leviarcoin-gui-wallet/monero/build/release/src/wallet: Not a directory
make: Entering directory '/home'
make: *** No rule to make target 'version'.  Stop.
make: Leaving directory '/home'
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
~/leviarcoin-gui-wallet
./get_libwallet_api.sh: line 224: pushd: /home/Shauli/leviarcoin-gui-wallet/monero/build/release/src/daemon: Not a directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
./get_libwallet_api.sh: line 227: popd: directory stack empty
make: *** /home/Shauli/leviarcoin-gui-wallet/monero/build/release/contrib/epee: Not a directory.  Stop.
make: *** /home/Shauli/leviarcoin-gui-wallet/monero/build/release/external/easylogging++: Not a directory.  Stop.
make: *** /home/Shauli/leviarcoin-gui-wallet/monero/build/release/external/db_drivers/liblmdb: Not a directory.  Stop.
Installing libunbound...
./get_libwallet_api.sh: line 241: pushd: /home/Shauli/leviarcoin-gui-wallet/monero/build/release/external/unbound: Not a directory
make: *** No rule to make target 'install'.  Stop.
./get_libwallet_api.sh: line 245: popd: directory stack empty
./get_libwallet_api.sh: line 248: popd: directory stack empty
make: Entering directory '/home/Shauli/leviarcoin-gui-wallet/src/zxcvbn-c'
g++ -I. -std=c++11 -O2 -Wall -Wextra \
        -o dictgen dict-generate.cpp
make: g++: Command not found
make: *** [makefile:61: dictgen] Error 127
make: Leaving directory '/home/Shauli/leviarcoin-gui-wallet/src/zxcvbn-c'
```

**Comment by markmatroska** [comment]
Hello, did you installed all the dependencies in mingw64? 
leviar-cli (the code to put in monero dir) will be published today on the respective repository

**Comment by Firefds** [comment]
Yes, I followed the readme step by step.
Also, there is no monero dir in the repository.

**Comment by Firefds** [comment]
I reinstalled the dependencies i mingw64.
Now i'm getting this errors after the `./build.sh` command:
`Building release
~/leviarcoin-gui-wallet ~/leviarcoin-gui-wallet
~/leviarcoin-gui-wallet ~/leviarcoin-gui-wallet
': not a valid identifierline 88: export: `dashless
': not a valid identifierline 88: export: `dashless
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
You are currently on commit 6a15368
The most recent tag was at 6a15368
You are building a tagged release
fatal: No annotated tags can describe '6a15368ed517f899a4656f56390147458439a3eb'.
However, there were unannotated tags: try --tags.
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
fatal: cannot change to '/home/Shauli/leviarcoin-gui-wallet/monero': Not a directory
libwallet_merged.a not found - Building libwallet
./get_libwallet_api.sh: line 82: /home/Shauli/leviarcoin-gui-wallet/monero/version.sh: Not a directory
Building libwallet release
cleaning up existing monero build dir, libs and includes
mkdir: cannot create directory ‘/home/Shauli/leviarcoin-gui-wallet/monero’: Not a directory
./get_libwallet_api.sh: line 129: pushd: /home/Shauli/leviarcoin-gui-wallet/monero/build/release: Not a directory
Configuring build for MINGW64..
CMake Error: The source directory "D:/msys64/home" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
./get_libwallet_api.sh: line 215: pushd: /home/Shauli/leviarcoin-gui-wallet/monero/build/release/src/wallet: Not a directory
make: Entering directory '/home'
make: *** No rule to make target 'version'.  Stop.
make: Leaving directory '/home'
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
~/leviarcoin-gui-wallet
./get_libwallet_api.sh: line 224: pushd: /home/Shauli/leviarcoin-gui-wallet/monero/build/release/src/daemon: Not a directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
./get_libwallet_api.sh: line 227: popd: directory stack empty
make: *** /home/Shauli/leviarcoin-gui-wallet/monero/build/release/contrib/epee: Not a directory.  Stop.
make: *** /home/Shauli/leviarcoin-gui-wallet/monero/build/release/external/easylogging++: Not a directory.  Stop.
make: *** /home/Shauli/leviarcoin-gui-wallet/monero/build/release/external/db_drivers/liblmdb: Not a directory.  Stop.
Installing libunbound...
./get_libwallet_api.sh: line 241: pushd: /home/Shauli/leviarcoin-gui-wallet/monero/build/release/external/unbound: Not a directory
make: *** No rule to make target 'install'.  Stop.
./get_libwallet_api.sh: line 245: popd: directory stack empty
./get_libwallet_api.sh: line 248: popd: directory stack empty
make: Entering directory '/home/Shauli/leviarcoin-gui-wallet/src/zxcvbn-c'
g++ -I. -std=c++11 -O2 -Wall -Wextra \
        -o dictgen dict-generate.cpp
dict-generate.cpp: In function 'void CreateArrays(NodeSPtr, StringIntSet_t&, StringOfInts&, Uint64Vect&, UintVect&)':
dict-generate.cpp:887:43: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'std::__cxx11::basic_string<int>::size_type {aka long long unsigned int ' [-Wformat=]
         snprintf(Tmp, sizeof Tmp, "%lu", x);
                                           ^
./dictgen -o dict-src.h words-eng_wiki.txt words-female.txt words-male.txt words-passwd.txt words-surname.txt words-tv_film.txt
cc -I. -O2 -Wall -Wextra -Wdeclaration-after-statement -c -o zxcvbn-inline.o zxcvbn.c
ar cvq libzxcvbn.a zxcvbn-inline.o
a - zxcvbn-inline.o
cc -I. -O2 -Wall -Wextra -Wdeclaration-after-statement -o test-statlib test.c libzxcvbn.a  -lm
make: Leaving directory '/home/Shauli/leviarcoin-gui-wallet/src/zxcvbn-c'
You are currently on commit 6a15368
The most recent tag was at 6a15368
You are building a tagged release
fatal: No annotated tags can describe '6a15368ed517f899a4656f56390147458439a3eb'.
However, there were unannotated tags: try --tags.
./build.sh: line 102: pushd: monero: Not a directory
You are currently on commit 6a15368
The most recent tag was at 6a15368
You are building a tagged release
fatal: No annotated tags can describe '6a15368ed517f899a4656f56390147458439a3eb'.
However, there were unannotated tags: try --tags.
~/leviarcoin-gui-wallet
Info: creating stash file D:\msys64\home\Shauli\leviarcoin-gui-wallet\build\.qmake.stash
Project MESSAGE: Host is 64bit
Project MESSAGE: Target is 32bit
Project MESSAGE: Host is 64bit
Project MESSAGE: Target is 32bit
WARNING: Failure to find: release/leviar_res.o
Project MESSAGE: Host is 64bit
Project MESSAGE: Target is 32bit
WARNING: Failure to find: debug/leviar_res.o
make -f Makefile.Release
make[1]: Entering directory '/home/Shauli/leviarcoin-gui-wallet/build'
D:/msys64/mingw64/bin\lrelease.exe -compress -nounfinished -removeidentical ../translations/leviar.ts -qm D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar.qm
D:/msys64/mingw64/bin\lrelease.exe -compress -nounfinished -removeidentical ../translations/leviar_pt-br.ts -qm D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_pt-br.qm
D:/msys64/mingw64/bin\lrelease.exe -compress -nounfinished -removeidentical ../translations/leviar_de.ts -qm D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_de.qm
D:/msys64/mingw64/bin\lrelease.exe -compress -nounfinished -removeidentical ../translations/leviar_eo.ts -qm D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_eo.qm
Updating 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_eo.qm'...
Removing translations equal to source text in 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_eo.qm'...
Updating 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_pt-br.qm'...
Removing translations equal to source text in 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_pt-br.qm'...
Updating 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar.qm'...
Removing translations equal to source text in 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar.qm'...
    Generated 0 translation(s) (0 finished and 0 unfinished)
    Ignored 454 untranslated source text(s)
    Generated 365 translation(s) (365 finished and 0 unfinished)
    Ignored 72 untranslated source text(s)
    Generated 436 translation(s) (436 finished and 0 unfinished)
Updating 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_de.qm'...
Removing translations equal to source text in 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_de.qm'...
    Generated 319 translation(s) (319 finished and 0 unfinished)
    Ignored 91 untranslated source text(s)
D:/msys64/mingw64/bin\lrelease.exe -compress -nounfinished -removeidentical ../translations/leviar_es.ts -qm D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_es.qm
D:/msys64/mingw64/bin\lrelease.exe -compress -nounfinished -removeidentical ../translations/leviar_fr.ts -qm D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_fr.qm
D:/msys64/mingw64/bin\lrelease.exe -compress -nounfinished -removeidentical ../translations/leviar_it.ts -qm D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_it.qm
D:/msys64/mingw64/bin\lrelease.exe -compress -nounfinished -removeidentical ../translations/leviar_nl.ts -qm D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_nl.qm
Updating 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_es.qm'...
Removing translations equal to source text in 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_es.qm'...
    Generated 422 translation(s) (422 finished and 0 unfinished)
    Ignored 2 untranslated source text(s)
Updating 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_fr.qm'...
Removing translations equal to source text in 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_fr.qm'...
    Generated 420 translation(s) (420 finished and 0 unfinished)
D:/msys64/mingw64/bin\lrelease.exe -compress -nounfinished -removeidentical ../translations/leviar_pl.ts -qm D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_pl.qm
D:/msys64/mingw64/bin\lrelease.exe -compress -nounfinished -removeidentical ../translations/leviar_ru.ts -qm D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_ru.qm
Updating 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_it.qm'...
Removing translations equal to source text in 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_it.qm'...
    Generated 428 translation(s) (428 finished and 0 unfinished)
    Ignored 1 untranslated source text(s)
Updating 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_nl.qm'...
Removing translations equal to source text in 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_nl.qm'...
    Generated 443 translation(s) (443 finished and 0 unfinished)
D:/msys64/mingw64/bin\lrelease.exe -compress -nounfinished -removeidentical ../translations/leviar_pt-pt.ts -qm D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_pt-pt.qm
windres -i ../leviar.rc -o release/leviar_res.o --include-dir=./.. -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN
Updating 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_pl.qm'...
Removing translations equal to source text in 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_pl.qm'...
    Generated 439 translation(s) (439 finished and 0 unfinished)
Updating 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_ru.qm'...
Removing translations equal to source text in 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_ru.qm'...
Updating 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_pt-pt.qm'...
Removing translations equal to source text in 'D:/msys64/home/Shauli/leviarcoin-gui-wallet/build/release/bin/translations/leviar_pt-pt.qm'...
    Generated 440 translation(s) (440 finished and 0 unfinished)
    Ignored 12 untranslated source text(s)
    Generated 435 translation(s) (435 finished and 0 unfinished)
g++ -c -fno-keep-inline-dllexport -march=nocona -mtune=core2 -Wa,-mbig-obj -fPIC -fstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -O2 -std=gnu++11 -Wall -W -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I../../leviarcoin-gui-wallet -I. -ID:/msys64/home/Shauli/leviarcoin-gui-wallet/monero/include -I../src/libwalletqt -I../src/QR-Code-generator -I../src -ID:/msys64/home/Shauli/leviarcoin-gui-wallet/monero/src -I../../../../mingw64/include/QtQuick -I../../../../mingw64/include/QtWidgets -I../../../../mingw64/include/QtGui -I../../../../mingw64/include/QtQml -I../../../../mingw64/include/QtNetwork -I../../../../mingw64/include/QtCore -Irelease -I../../../../mingw64/include -I../../../../mingw64/share/qt5/mkspecs/win32-g++  -o release/main.o ../main.cpp
g++ -c -fno-keep-inline-dllexport -march=nocona -mtune=core2 -Wa,-mbig-obj -fPIC -fstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -O2 -std=gnu++11 -Wall -W -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I../../leviarcoin-gui-wallet -I. -ID:/msys64/home/Shauli/leviarcoin-gui-wallet/monero/include -I../src/libwalletqt -I../src/QR-Code-generator -I../src -ID:/msys64/home/Shauli/leviarcoin-gui-wallet/monero/src -I../../../../mingw64/include/QtQuick -I../../../../mingw64/include/QtWidgets -I../../../../mingw64/include/QtGui -I../../../../mingw64/include/QtQml -I../../../../mingw64/include/QtNetwork -I../../../../mingw64/include/QtCore -Irelease -I../../../../mingw64/include -I../../../../mingw64/share/qt5/mkspecs/win32-g++  -o release/filter.o ../filter.cpp
g++ -c -fno-keep-inline-dllexport -march=nocona -mtune=core2 -Wa,-mbig-obj -fPIC -fstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -O2 -std=gnu++11 -Wall -W -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I../../leviarcoin-gui-wallet -I. -ID:/msys64/home/Shauli/leviarcoin-gui-wallet/monero/include -I../src/libwalletqt -I../src/QR-Code-generator -I../src -ID:/msys64/home/Shauli/leviarcoin-gui-wallet/monero/src -I../../../../mingw64/include/QtQuick -I../../../../mingw64/include/QtWidgets -I../../../../mingw64/include/QtGui -I../../../../mingw64/include/QtQml -I../../../../mingw64/include/QtNetwork -I../../../../mingw64/include/QtCore -Irelease -I../../../../mingw64/include -I../../../../mingw64/share/qt5/mkspecs/win32-g++  -o release/clipboardAdapter.o ../clipboardAdapter.cpp
g++ -c -fno-keep-inline-dllexport -march=nocona -mtune=core2 -Wa,-mbig-obj -fPIC -fstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -O2 -std=gnu++11 -Wall -W -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I../../leviarcoin-gui-wallet -I. -ID:/msys64/home/Shauli/leviarcoin-gui-wallet/monero/include -I../src/libwalletqt -I../src/QR-Code-generator -I../src -ID:/msys64/home/Shauli/leviarcoin-gui-wallet/monero/src -I../../../../mingw64/include/QtQuick -I../../../../mingw64/include/QtWidgets -I../../../../mingw64/include/QtGui -I../../../../mingw64/include/QtQml -I../../../../mingw64/include/QtNetwork -I../../../../mingw64/include/QtCore -Irelease -I../../../../mingw64/include -I../../../../mingw64/share/qt5/mkspecs/win32-g++  -o release/oscursor.o ../oscursor.cpp
In file included from ../main.cpp:42:0:
../src/libwalletqt/WalletManager.h:6:10: fatal error: wallet/api/wallet2_api.h: No such file or directory
 #include <wallet/api/wallet2_api.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.Release:2573: release/main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/Shauli/leviarcoin-gui-wallet/build'
make: *** [Makefile:36: release] Error 2
`

**Comment by markmatroska** [comment]
You need to clone cli git repo in subdirectory 'monero' the build script will compile the needed code from cli sources then the gui.
